FROM ubuntu:latest
ARG DEBIAN_FRONTEND=noninteractive
LABEL maintainer="joygram <joygram@gmail.com>"

RUN apt update
RUN apt-get update 
RUN apt upgrade -y 

RUN apt-get install -y git 
RUN apt-get install -y sudo 
RUN apt-get install -y curl
RUN apt-get install -y vim 
RUN apt-get install -y tzdata 
RUN apt-get install -y openssh-server 
RUN apt-get install -y gdebi-core 
RUN apt-get install -y r-base r-cran-devtools 
RUN apt-get install -y fonts-lmodern fonts-nanum fonts-unfonts-extra 
RUN apt-get install -y apt-utils
RUN apt-get install -y apache2
RUN apt-get install -y libcairo2-dev 
RUN apt-get install -y libssl-dev libclang-dev
RUN apt-get install -y texlive-xetex 

# update apt for php 
RUN apt install -y software-properties-common ca-certificates lsb-release apt-transport-https 
RUN LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php 


# nodejs 18 and yarn  and apache2
RUN apt -y purge nodejs 
RUN apt -y autoremove

# install nodejs 
RUN wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
# RUN wget -O - https://deb.nodesource.com/setup_current.x | bash -
# RUN apt-get install -y nodejs

RUN apt-get install -y yarn 

# install php8 
RUN apt install php8.1 -y

# install etc 

# install mariadb 

RUN curl -LsS -O https://downloads.mariadb.com/MariaDB/mariadb_repo_setup
RUN bash mariadb_repo_setup --mariadb-server-version=10.7

RUN apt install -y mariadb-server mariadb-client 

#server settings 
WORKDIR /home/install
COPY install_scripts /home/install

RUN R -f ./install_packages.R

## install R base packages 
RUN cp /usr/local/lib/R/site-library/littler/examples/install2.r /usr/bin/

# install r packages 
RUN install2.r bs4cards clusterSim DALEX DALEXtra EnvStats flexdashboard ggrepel gt
RUN install2.r janitor keras mixdist modelStudio plotly r2d3 ranger reshape2 rsconnect shinythemes tidymodels
RUN install2.r KernSmooth MASS Matrix class lattice mgcv nlme gridlayout learnr      
RUN install2.r devtools DBI DT DiagrammeR R6 RColorBrewer Rcpp Rttf2pt1 askpass assertthat  
RUN install2.r backports base64enc bit bit64 blob broom      
RUN install2.r bslib cachem callr cellranger checkmate classInt    
RUN install2.r cli clipr colourpicker colorspace commonmark cpp11 crayon crosstalk curl        
RUN install2.r data.table dbplyr digest dlookr downloader dplyr dtplyr digest
RUN install2.r e1071 ellipsis evaluate extrafont extrafontdb 
RUN install2.r fansi farver fastmap flextable fontawesome forcats fresh fs 
RUN install2.r gargle gdtools generics ggplot2 glue googledrive googlesheets gridExtra gtable
RUN install2.r haven here highr hms htmltools htmlwidgets httpuv httr        
RUN install2.r ids igraph influenceR isoband jquerylib jsonlite kableExtra knitr labeling later       
RUN install2.r lazyeval lifecycle lubridate magrittr markdown memoise mime modelr munsell officer openssl openxlsx 
RUN install2.r pillar pkgconfig prettyunits processx progress promises proxy ps purrr rappdirs readr readxl      
RUN install2.r rematch rematch2 reprex reticulate rlang rmarkdown rprojroot rstudioapi rvest s2 sass scales selectr     
RUN install2.r sf shiny shinyAce shinycssload shinydashboa shinybusy shinydashboa shinyWidgets shinyjs shinytheme showtext showtextdb sourcetools 
RUN install2.r stringi stringr svglite sys sysfonts systemfonts 
RUN install2.r tibble tidyr tidyselect tidyverse tinytex 
RUN install2.r tzdb units utf8 uuid vctrs viridis viridisLite visNetwork vroom waiter webshot withr wk          
RUN install2.r xfun xml2 xtable yaml zip      
# for bitStat 
RUN install2.r gdtools flextable dlookr alookr

# install shinylive, quarto, etc.
RUN ./install_packages.sh

#make bit-server account 
RUN useradd -m bit
RUN echo "bit:bit" | chpasswd 
RUN usermod -d /home/bit-server bit
RUN usermod -aG sudo bit
RUN gpasswd -a bit bit 

# add locale 
RUN apt-get install locales -y 
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# setup workspace 
RUN git clone https://github.com/joygram/bit-server.git /home/bit-server

WORKDIR /home/bit-server
RUN cp /home/install/.bash* /home/bit-server/
RUN cp /home/install/.bash* ~/
RUN chown bit:bit -R /home/bit-server


#  apache2 apache2-ssl ssh rstudio-server shiny-server 
EXPOSE 80 22 443 8787 3838

# additional apache setting
RUN a2enmod proxy proxy_http proxy_wstunnel rewrite

RUN chsh bit -s /usr/bin/bash 
RUN chsh root -s /usr/bin/bash 

# clean up apt cache 
RUN apt-get clean autoclean
RUN apt-get autoremove --yes
RUN rm -rf /var/lib/{apt,dpkg,cache,log}/

## 패치 및 설정 반영 
CMD ["bash", "/home/bit-server/scripts/update.sh"]